### ISSUE TITLE
host the Youtube-dl

### ISSUE THREAD

**Issue by elmersaid** [cuongpm/youtube-dl-android#5]
how did you host the Youtube-dl on herokuapp can i get source please ?

**Comment by cuongpm** [comment]
You can find the source code to host your own herokuapp here:
- https://github.com/jaimeMF/youtube-dl-api-server
- https://youtube-dl-api-server.readthedocs.io/en/latest/install.html

But it is a pretty old version of youtube-dl. If you want to use latest version of youtube-dl, you should update it by yourself or figure out other youtube-dl-api-server source.
